### ISSUE TITLE
关于mLastRawY=-1时的处理问题

### ISSUE THREAD

**Issue by gangoogle** [bauer-bao/DragCloseHelper#10]
我用了兄弟你的这个控件，在做transion动画时  move会经常先触发，之前的做法时return true 
这样会导致我的photoview无法进行放大  如果return false的话 会有一个问题就是感觉这个很不流畅 
我的做法是下面这样

`  if (mLastRawY == -1) {
                    log("action move--->" +"lastRawY=-1");
                    reset(event);
                    mLastY = event.getY();
                    mLastX = event.getX();
                    mLastRawY = event.getRawY();
                    mLastRawX = event.getRawX();
                    //开始按
                    isPress = true;
                    //初始化数据
                    lastPointerId = event.getPointerId(0);
                }`

**Comment by gangoogle** [comment]
``` 
if (mLastRawY == -1) {
                    log("action move--->" +"lastRawY=-1");
                    reset(event);
                    mLastY = event.getY();
                    mLastX = event.getX();
                    mLastRawY = event.getRawY();
                    mLastRawX = event.getRawX();
                    //开始按
                    isPress = true;
                    //初始化数据
                    lastPointerId = event.getPointerId(0);
                }
```

**Comment by bauer-bao** [comment]
你好兄弟，感谢提issue。确实有点问题。

**Comment by bauer-bao** [comment]
兄弟，我确认了下，按照我的代码的话，测得结果就是，没法双指手势放大。如果只是这个问题的话，感觉和那块代码没有太大关系。

**Comment by bauer-bao** [comment]
兄弟，可以帮忙在最新的版本上验证下是否解决么？3Q
