### ISSUE TITLE
使用出现问题，比较疑惑

### ISSUE THREAD

**Issue by fingdo** [bauer-bao/DragCloseHelper#11]
A->B，B是预览图片界面，B设置了透明主题，然后通过DragHelper去设置透明度，发现看不到A的界面元素。如果熄屏亮屏再操作就可以看到A的界面元素，这个问题怎么解决呢？麻烦了

**Comment by fingdo** [comment]
QQ178357820，可以私聊一起讨论一下

**Comment by bauer-bao** [comment]
经讨论，已经解决问题。
