### ISSUE TITLE
图片预览页面沉浸式失败和图片缩放手势与viewpager冲突

### ISSUE THREAD

**Issue by magic0908** [bauer-bao/DragCloseHelper#12]
感谢作者开源，不过我这边发现demo的两个问题。
1、在九宫格页点击图片到放大，图片起始位置只占整个格子的一半；到最终放大的时候，会出现短暂的位置偏差。
2、双指缩放冲突，我看了其他issue，说在intercept处理，demo也写了相应逻辑，但是还是有问题。
测试机型，小米8，9.0系统

**Comment by bauer-bao** [comment]
感谢使用。
问题1，暂不处理，微信朋友圈也有这问题。
问题2，问题可以说的再详细些么？我好方便有针对性的排查。

**Comment by magic0908** [comment]
不好意思我描述清楚些，
问题1，我看了微信朋友圈，很自然的从小图过渡到大图，并没有图片显示偏差这个问题啊；
问题2，图片预览的时候，双指将图片放大，会出现和viewpager的冲突

**Comment by bauer-bao** [comment]
问题1.我用demo生成gif，并且已经替换了，感觉没有你说的情况啊。你可以再比对比对。
问题2.因为本库是在dispatchTouchEvent拦截整体的触摸事件，然后判断是竖直方向的手势的话，才会去处理滑动返回逻辑。如果是水平方向的手势，就交给系统继续下发事件，这时候，viewpager和imageview都会获取事件。得需要花时间看看。

**Comment by magic0908** [comment]
![image](https://user-images.githubusercontent.com/23170601/71138848-b13feb00-2247-11ea-9994-6a3ee6168f8d.png)
zhe's这是我录的一个GIF，点开第七张图的时候反映比较明显的位置偏差，就是图片渐变到最大的时候，过一会才往中间偏

**Comment by magic0908** [comment]
好像传不了gif。。

**Comment by bauer-bao** [comment]
兄弟，加你Q了，同意下。

**Comment by magic0908** [comment]
我这边没收到消息。。我的QQ：947314264
或者我加你也行

**Comment by bauer-bao** [comment]
_QQ是你github注册邮箱上看到的。_
经私下确认讨论，结果如下：
问题1，现象：图片预览页面状态栏文字隐藏了，但是状态栏背景色还显示着。根源：全屏代码兼容性问题。解决：使用开发项目中的全屏方案即可。
问题2，现象：vp的左右滑动和pv的缩放手势相冲突。根源：非库的问题，将库注释掉，仍然存在。解决：使用HackyViewPager，并且实现pv的onMatrixChangeListener，根据不同状态去决定是否拦截vp的滑动事件。具体代码请查看demo
