### ISSUE TITLE
效果很差

### ISSUE THREAD

**Issue by Licarey** [bauer-bao/DragCloseHelper#13]
效果太差了

**Comment by bauer-bao** [comment]
感谢您的反馈。是否有更加具体的描述，比如是哪里的效果不好？我可以优化下

**Comment by Licarey** [comment]
> 感谢您的反馈。是否有更加具体的描述，比如是哪里的效果不好？我可以优化下
就是图片拖拽归回原位的时候，衔接很不流畅，原位的图片是正方形的，拖拽的图片是长方形的 所以看着不好。我没看你的具体实现是view的坐标记录实现的 还是共享元素实现的

**Comment by bauer-bao** [comment]
共享元素去实现的。本库是基于共享元素的，仅对滑动返回做了动画处理。其他逻辑，还是由共享元素系统自己实现。
你说的问题，确实是一个体验问题。因为原位的图片，正常情况下，都是用centercrop属性，而大图一般都是正常显示，所以切换的时候，看着有点不舒服。
