### ISSUE TITLE
微信朋友圈那种预览效果

### ISSUE THREAD

**Issue by RuoYuHoney** [bauer-bao/DragCloseHelper#3]
如果是一个九宫格，点击第一张图片预览，然后左滑到第二张图片，再拖动返回上个页面，需要回到九宫格的第二个图片位置。。。。怎么实现（微信朋友圈那种）？

**Comment by bauer-bao** [comment]
兄弟，那功能都是通过共享元素动画实现的。可以参考 https://www.jianshu.com/p/50f62d9e60e1

**Comment by bauer-bao** [comment]
兄弟，微信的手势逻辑代码是加在预览图片的photoView里面的，我的是在外面处理的，所以效果略有不同。但是你说的那个功能，我在demo中有更新，还是参考上面给的链接。主要是共享元素这块的知识点，和库没有多大关系。感谢支持。
