### ISSUE TITLE
与ViewPager结合左右滑动，手势冲突

### ISSUE THREAD

**Issue by HelloPeng** [bauer-bao/DragCloseHelper#4]
大佬，出现这种问题，应该怎么解决

**Comment by bauer-bao** [comment]
兄弟，监听中有个intercept方法，false表示不拦截，你可以检测viewpager的滚动事件，如果开始滚动了，就返回true，如果不滚动，就返回false。

**Comment by HelloPeng** [comment]
好的

**Comment by bauer-bao** [comment]
兄弟，没问题了吧？我关了。有问题再开issue吧。

**Comment by HelloPeng** [comment]
我把左右滑的手势给你那边直接拦截了，我看小米系统的相册，左右滑也不能关闭。话说你那边也可以自己写个Demo试一试啊，看看怎么处理用户体验更好，也给一个解决方案啥的

**Comment by bauer-bao** [comment]
好的，感谢你的建议。我更新了一版，demo也改成了vp。稍微优化了滑动冲突的体验。只需将0.0.8改成0.0.9即可。再次感谢。
