### ISSUE TITLE
拖拽后, 执行退出动画过程中, 底部虚拟导航栏和顶部状态栏会突然显示图片

### ISSUE THREAD

**Issue by hanlichao** [bauer-bao/DragCloseHelper#5]
拖拽后, 执行退出动画过程中, 底部虚拟导航栏和顶部状态栏会突然显示图片, 拖拽中是不显示的

**Comment by hanlichao** [comment]
是执行下方代码过程中出现
//拖拽关闭，如果是共享元素的页面，需要执行activity的onBackPressed方法，注意如果使用finish方法，则返回的时候没有共享元素的返回动画
if (isShareElementMode) {
    onBackPressed();
}

**Comment by bauer-bao** [comment]
嗯，我知道这个现象，我自己没在意。因为拖拽是本库的实现，你说的现象，其实已经算是共享元素这块的知识点了，和库没有直接关系。我有看微信的效果，他们是不管拖拽还是后面的动画效果，图片都会在虚拟键盘上显示。我看看能不能和微信效果保持一致。可能需要些时间。

**Comment by bauer-bao** [comment]
看了下微信，他其实是把布局沉浸式到了虚拟导航栏下面去了，然后还不显示状态栏。所以，这个现象如果要处理的话，可能也要做微信类似的处理。和库没有直接关联。

**Comment by hanlichao** [comment]
对的

**Comment by bauer-bao** [comment]
我确认了是这样的，getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);
只要在activity中添加这行代码，设置半透明的导航栏，表现形式就和微信一样了。你可以试试。至于状态栏，就看你项目具体的需求而设置不同的属性了。
