### ISSUE TITLE
demo里能不能加入Recycleview列表的应用场景?

### ISSUE THREAD

**Issue by cbuemc** [bauer-bao/DragCloseHelper#7]
demo里能不能加入Recycleview列表的应用场景

**Comment by bauer-bao** [comment]
你想要什么样式的？线性还是网格样式？

**Comment by cbuemc** [comment]
就类似朋友圈那种，九宫格列表
 
------------------
----------------------------------------------------我是华丽的分割线
邓毅
中国电信天翼电子商务有限公司广东分公司
信息技术部
E-Mail：19843400@qq.com

手机号码：15815811884

办公地址：广州市天河区华利路19号远洋明珠大厦2楼



 




------------------ 原始邮件 ------------------
发件人: "bauer-bao"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 中午11:59
收件人: "bauer-bao/DragCloseHelper"<DragCloseHelper@noreply.github.com>; 
抄送: "ㄓ魅力??旋风"<19843400@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [bauer-bao/DragCloseHelper] demo里能不能加入Recycleview列表的应用场景? (#7)




你想要什么样式的？线性还是网格样式？

**Comment by cbuemc** [comment]
> 你想要什么样式的？线性还是网格样式？

类似朋友圈的九宫格列表

**Comment by bauer-bao** [comment]
好的，有时间我改下。

**Comment by cbuemc** [comment]
> 好的，有时间我改下。

好的，谢谢，因为我对着你demo想弄成列表的，发觉自己不太会搞，而且要用Eventbus传来传去，看得我一脸懵逼，所以最好demo有示例，看着更容易明白，可能是我太菜了

**Comment by bauer-bao** [comment]
已修改。没办法，要更新共享元素的值，只能通过eventbus等消息bus传递。
