### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by jasonlee3652** [bauer-bao/DragCloseHelper#8]
可以新增点击图片关闭以及长按事件监听这两个功能吗，类似微信朋友圈浏览图片的效果。另外在Fragment中怎么实现最好

**Comment by bauer-bao** [comment]
我大概看了下，单击关闭的话，好处理，可以直接在你自己的view上添加就可以了。但是长按的话，因为长按是down事件的时候就触发了长按计时事件，我的库是在move的时候才能确定是否开始滑动，所以不太好拦截。
如果在库中处理单击和长按的话，我需要多花点时间看看（包括在fragment中处理滑动返回）。
感谢支持和意见。

**Comment by jasonlee3652** [comment]
我改了下，可以实现这两个点击事件的监听，作者看下我这样写有问题没
`package com.dragclosehelper.library;

import android.animation.Animator;
import android.animation.ValueAnimator;
import android.app.Activity;
import android.content.Context;
import android.util.Log;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewConfiguration;
import android.view.animation.LinearInterpolator;

import androidx.annotation.FloatRange;

/**
 * @author bauer on 2019/4/17.
 */
public class DragCloseHelper {
    private ViewConfiguration viewConfiguration;

    /**
     * 动画执行时间
     */
    private final static long DURATION = 100;
    /**
     * 滑动边界距离
     */
    private final static int MAX_EXIT_Y = 500;
    private int maxExitY = MAX_EXIT_Y;
    /**
     * 最小的缩放尺寸
     */
    private static final float MIN_SCALE = 0.4F;
    private float minScale = MIN_SCALE;
    /**
     * 是否在滑动关闭中，手指还在触摸中
     */
    private boolean isSwipingToClose;
    /**
     * 上次触摸坐标
     */
    private float mLastY, mLastRawY, mLastX, mLastRawX;
    /**
     * 上次触摸手指id
     */
    private int lastPointerId;
    /**
     * 当前位移距离
     */
    private float mCurrentTranslationY, mCurrentTranslationX;
    /**
     * 上次位移距离
     */
    private float mLastTranslationY, mLastTranslationX;
    /**
     * 正在恢复原位中
     */
    private boolean isResetingAnimate = false;
    /**
     * 共享元素模式
     */
    private boolean isShareElementMode = false;

    private View parentV, childV;

    private DragCloseListener dragCloseListener;
    private Context mContext;

    private boolean isDebug = false;

    private boolean mHasPerformedLongPress;
    public int mPrivateFlags;
    private static final int PFLAG_PRESSED = 0x00004000;
    private CheckForLongPress mPendingCheckForLongPress;
    int mWindowAttachCount;

    private float mLongClickX = Float.NaN;
    private float mLongClickY = Float.NaN;

    public DragCloseHelper(Context mContext) {
        this.mContext = mContext;
        viewConfiguration = ViewConfiguration.get(mContext);
    }

    public void setDragCloseListener(DragCloseListener dragCloseListener) {
        this.dragCloseListener = dragCloseListener;
    }

    /**
     * 设置共享元素模式
     *
     * @param shareElementMode
     */
    public void setShareElementMode(boolean shareElementMode) {
        isShareElementMode = shareElementMode;
    }

    /**
     * 设置拖拽关闭的view
     *
     * @param parentV
     * @param childV
     */
    public void setDragCloseViews(View parentV, View childV) {
        this.parentV = parentV;
        this.childV = childV;
    }

    /**
     * 设置最大退出距离
     *
     * @param maxExitY
     */
    public void setMaxExitY(int maxExitY) {
        this.maxExitY = maxExitY;
    }

    /**
     * 设置最小缩放尺寸
     *
     * @param minScale
     */
    public void setMinScale(@FloatRange(from = 0.1f, to = 1.0f) float minScale) {
        this.minScale = minScale;
    }

    /**
     * 设置debug模式
     *
     * @param debug
     */
    public void setDebug(boolean debug) {
        isDebug = debug;
    }

    public void setPressed(boolean pressed) {
        if (pressed) {
            mPrivateFlags |= PFLAG_PRESSED;
        } else {
            mPrivateFlags &= ~PFLAG_PRESSED;
        }
    }

    public boolean isPressed() {
        return (mPrivateFlags & PFLAG_PRESSED) == PFLAG_PRESSED;
    }

    public boolean performLongClick() {
        return dragCloseListener != null && dragCloseListener.onLongClick(parentV);
    }

    public boolean performLongClick(float x, float y) {
        mLongClickX = x;
        mLongClickY = y;
        final boolean handled = performLongClick();
        mLongClickX = Float.NaN;
        mLongClickY = Float.NaN;
        return handled;
    }

    private final class CheckForLongPress implements Runnable {
        private int mOriginalWindowAttachCount;
        private float mX;
        private float mY;
        private boolean mOriginalPressedState;

        @Override
        public void run() {
            if ((mOriginalPressedState == isPressed())
                    && mOriginalWindowAttachCount == mWindowAttachCount) {
                if (performLongClick(mX, mY)) {
                    mHasPerformedLongPress = true;
                }
            }
        }

        public void setAnchor(float x, float y) {
            mX = x;
            mY = y;
        }

        public void rememberWindowAttachCount() {
            mOriginalWindowAttachCount = mWindowAttachCount;
        }

        public void rememberPressedState() {
            mOriginalPressedState = isPressed();
        }
    }


    private void checkForLongClick(int delayOffset, float x, float y) {
        mHasPerformedLongPress = false;

        if (mPendingCheckForLongPress == null) {
            mPendingCheckForLongPress = new CheckForLongPress();
        }
        mPendingCheckForLongPress.setAnchor(x, y);
        mPendingCheckForLongPress.rememberWindowAttachCount();
        mPendingCheckForLongPress.rememberPressedState();
        parentV.postDelayed(mPendingCheckForLongPress,
                ViewConfiguration.getLongPressTimeout() - delayOffset);
    }

    /**
     * 处理touch事件
     *
     * @param event
     * @return
     */
    public boolean handleEvent(MotionEvent event) {
        float currentY = event.getY();
        float currentX = event.getX();
        if (dragCloseListener != null && dragCloseListener.intercept()) {
            //拦截
            log("action dispatch--->");
            isSwipingToClose = false;
            return false;
        } else {
            //不拦截
            if (event.getAction() == MotionEvent.ACTION_DOWN) {
                log("action down--->");
                mHasPerformedLongPress = false;

                setPressed(true);
                checkForLongClick(0, currentX, currentY);

                //初始化数据
                lastPointerId = event.getPointerId(0);
                reset(event);
            } else if (event.getAction() == MotionEvent.ACTION_MOVE) {
                log("action move--->" + event.getPointerCount() + "---" + isSwipingToClose);
                if (mLastRawX != event.getRawX() && mLastRawY != event.getRawY()) {
                    parentV.removeCallbacks(mPendingCheckForLongPress);
                    if ((mPrivateFlags & PFLAG_PRESSED) != 0) {
                        setPressed(false);
                    }
                }
                if (event.getPointerCount() > 1) {
                    //如果有多个手指
                    if (isSwipingToClose) {
                        //已经开始滑动关闭，恢复原状，否则需要派发事件
                        isSwipingToClose = false;
                        resetCallBackAnimation();
                        return true;
                    }
                    reset(event);
                    return false;
                }
                if (lastPointerId != event.getPointerId(0)) {
                    //手指不一致，恢复原状
                    if (isSwipingToClose) {
                        resetCallBackAnimation();
                    }
                    reset(event);
                    return true;
                }
                if (isSwipingToClose ||
                        (Math.abs(currentY - mLastY) > 2 * viewConfiguration.getScaledTouchSlop() && Math.abs(currentY - mLastY) > Math.abs(currentX - mLastX) * 1.5)) {
                    //已经触发或者开始触发，更新view
                    mLastY = currentY;
                    mLastX = currentX;
                    log("action move---> start close");
                    float currentRawY = event.getRawY();
                    float currentRawX = event.getRawX();
                    if (!isSwipingToClose) {
                        //准备开始
                        isSwipingToClose = true;
                        if (dragCloseListener != null) {
                            dragCloseListener.dragStart();
                        }
                    }
                    //已经开始，更新view
                    mCurrentTranslationY = currentRawY - mLastRawY + mLastTranslationY;
                    mCurrentTranslationX = currentRawX - mLastRawX + mLastTranslationX;
                    float percent = 1 - Math.abs(mCurrentTranslationY / (maxExitY + childV.getHeight()));
                    if (percent > 1) {
                        percent = 1;
                    } else if (percent < 0) {
                        percent = 0;
                    }
                    parentV.getBackground().mutate().setAlpha((int) (percent * 255));
                    if (dragCloseListener != null) {
                        dragCloseListener.dragging(percent);
                    }
                    childV.setTranslationY(mCurrentTranslationY);
                    childV.setTranslationX(mCurrentTranslationX);
                    if (percent < minScale) {
                        percent = minScale;
                    }
                    childV.setScaleX(percent);
                    childV.setScaleY(percent);
                    return true;
                }
            } else if (event.getAction() == MotionEvent.ACTION_UP) {
                log("action up--->" + isSwipingToClose);
                if ((mPrivateFlags & PFLAG_PRESSED) != 0) {
                    // take focus if we don't have it already and we should in
                    // touch mode.
                    boolean focusTaken = false;
                    if (parentV.isFocusable() && parentV.isFocusableInTouchMode() && !parentV.isFocused()) {
                        focusTaken = parentV.requestFocus();
                    }

                    if (!mHasPerformedLongPress) {
                        // This is a tap, so remove the longpress check
                        parentV.removeCallbacks(mPendingCheckForLongPress);

                        // Only perform take click actions if we were in the pressed state
                        if (!focusTaken) {
                            //会执行共享元素的离开动画
                            if (dragCloseListener != null) {
                                dragCloseListener.clickClose(parentV);
                            }
                        }
                    }
                }

                //手指抬起事件
                if (isSwipingToClose) {
                    if (mCurrentTranslationY > maxExitY) {
                        if (isShareElementMode) {
                            //会执行共享元素的离开动画
                            if (dragCloseListener != null) {
                                dragCloseListener.dragClose(true);
                            }
                        } else {
                            //会执行定制的离开动画
                            exitWithTranslation(mCurrentTranslationY);
                        }
                    } else {
                        resetCallBackAnimation();
                    }
                    isSwipingToClose = false;
                    return true;
                }
            } else if (event.getAction() == MotionEvent.ACTION_CANCEL) {
                //取消事件
                if (isSwipingToClose) {
                    resetCallBackAnimation();
                    isSwipingToClose = false;
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * 退出动画
     *
     * @param currentY
     */
    public void exitWithTranslation(float currentY) {
        int targetValue = currentY > 0 ? childV.getHeight() : -childV.getHeight();
        ValueAnimator anim = ValueAnimator.ofFloat(mCurrentTranslationY, targetValue);
        anim.addUpdateListener(animation -> updateChildView(mCurrentTranslationX, (float) animation.getAnimatedValue()));
        anim.addListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animation) {

            }

            @Override
            public void onAnimationEnd(Animator animation) {
                if (dragCloseListener != null) {
                    dragCloseListener.dragClose(false);
                }
                ((Activity) mContext).finish();
                ((Activity) mContext).overridePendingTransition(R.anim.dchlib_anim_empty, R.anim.dchlib_anim_alpha_out_long_time);
            }

            @Override
            public void onAnimationCancel(Animator animation) {

            }

            @Override
            public void onAnimationRepeat(Animator animation) {

            }
        });
        anim.setDuration(DURATION);
        anim.setInterpolator(new LinearInterpolator());
        anim.start();
    }

    /**
     * 重置数据
     *
     * @param event
     */
    private void reset(MotionEvent event) {
        isSwipingToClose = false;
        mLastY = event.getY();
        mLastX = event.getX();
        mLastRawY = event.getRawY();
        mLastRawX = event.getRawX();
        mLastTranslationY = 0;
        mLastTranslationX = 0;
    }

    /**
     * 更新缩放的view
     */
    private void updateChildView(float transX, float transY) {
        childV.setTranslationY(transY);
        childV.setTranslationX(transX);
        float percent = Math.abs(transY / (maxExitY + childV.getHeight()));
        float scale = 1 - percent;
        if (scale < minScale) {
            scale = minScale;
        }
        childV.setScaleX(scale);
        childV.setScaleY(scale);
    }

    /**
     * 恢复到原位动画
     */
    private void resetCallBackAnimation() {
        if (isResetingAnimate || mCurrentTranslationY == 0) {
            return;
        }
        float ratio = mCurrentTranslationX / mCurrentTranslationY;
        ValueAnimator animatorY = ValueAnimator.ofFloat(mCurrentTranslationY, 0);
        animatorY.addUpdateListener(valueAnimator -> {
            if (isResetingAnimate) {
                mCurrentTranslationY = (float) valueAnimator.getAnimatedValue();
                mCurrentTranslationX = ratio * mCurrentTranslationY;
                mLastTranslationY = mCurrentTranslationY;
                mLastTranslationX = mCurrentTranslationX;
                updateChildView(mLastTranslationX, mCurrentTranslationY);
            }
        });
        animatorY.addListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animation) {
                isResetingAnimate = true;
            }

            @Override
            public void onAnimationEnd(Animator animation) {
                if (isResetingAnimate) {
                    parentV.getBackground().mutate().setAlpha(255);
                    mCurrentTranslationY = 0;
                    mCurrentTranslationX = 0;
                    isResetingAnimate = false;
                    if (dragCloseListener != null) {
                        dragCloseListener.dragCancel();
                    }
                }
            }

            @Override
            public void onAnimationCancel(Animator animation) {

            }

            @Override
            public void onAnimationRepeat(Animator animation) {

            }
        });
        animatorY.setDuration(DURATION).start();
    }

    /**
     * 打印日志
     *
     * @param msg
     */
    private void log(String msg) {
        if (isDebug) {
            Log.d(getClass().getName(), msg);
        }
    }

    public interface DragCloseListener {
        /**
         * 是否有拦截
         *
         * @return
         */
        boolean intercept();

        /**
         * 开始拖拽
         */
        void dragStart();

        /**
         * 拖拽中
         *
         * @param percent
         */
        void dragging(float percent);

        /**
         * 取消拖拽
         */
        void dragCancel();

        /**
         * 拖拽结束并且关闭
         *
         * @param isShareElementMode
         */
        void dragClose(boolean isShareElementMode);

        /**
         * 点击事件
         */
        void clickClose(View v);

        /**
         * 长按事件
         */
        boolean onLongClick(View v);
    }
}
`

**Comment by jasonlee3652** [comment]
我改了下，增加了点击事件和长按事件的监听，作者看下我这样实现有问题没
[DragCloseHelper.java](https://github.com/jasonlee3652/DragCloseHelper/edit/master/library/src/main/java/com/dragclosehelper/library/DragCloseHelper.java)

**Comment by bauer-bao** [comment]
666，是不是参考的源码？感觉写的好多，实际自己写的话，不会那么多代码的。简单的在down和up处理下就完事了。但是两个回调（click和longclick）应该传递childview，而不是parentview。childview是实际拖动的view，parentview是拖动的时候的背景view。而且你拿到view之后需要强转一下，才能拿到你实际的view。感谢你的代码，我有时间我会添加此功能。
再次感谢。

**Comment by jasonlee3652** [comment]
那我就坐等作者更新了，另外还有两个小问题提一下，一个是全面屏手机的动画有点偏差，另一个是，如果快速点击两次网格中的View，会启动两个Activity，返回后网格就空白了一个格子

**Comment by bauer-bao** [comment]
第一个问题，我到时候测试看看。第二个问题，快速点击需要做防抖动处理，需要自己处理的。

**Comment by bauer-bao** [comment]
您好，库已经更新，添加了单击和长按事件。但是建议长按事件使用库中的方法，单击直接写在宿主app中，以免库的单击事件和view的单击事件重复甚至冲突。
    至于在fragment中怎么实现，因为fragment中没有dispatchtouchevent，所以没法将dragclosehelper放到fragment中。所以，只能放在app中，然后childview传framelayout，parentview传framelayout外面一层的layout。如果你还要知道当前点击/长按的图片的索引值，则必须将fragment中的viewpager当前选中的索引，通过接口或者其他方式通知给fragment的宿主activity（其实这样做还是有点麻烦的）。
    至于全面屏动画偏差，我这暂时没有真机，不太好测试。原则上动画都是用的系统的共享元素，所以和本库没有直接关联吧。
    再次感谢支持。

**Comment by bauer-bao** [comment]
您好，库已经更新，添加了单击和长按事件。但是建议长按事件使用库中的方法，单击直接写在宿主app中，以免库的单击事件和view的单击事件重复甚至冲突。
至于在fragment中怎么实现，因为fragment中没有dispatchtouchevent，所以没法将dragclosehelper放到fragment中。所以，只能放在app中，然后childview传framelayout，parentview传framelayout外面一层的layout。如果你还要知道当前点击/长按的图片的索引值，则必须将fragment中的viewpager当前选中的索引，通过接口或者其他方式通知给fragment的宿主activity（其实这样做还是有点麻烦的）。
至于全面屏动画偏差，我这暂时没有真机，不太好测试。原则上动画都是用的系统的共享元素，所以和本库没有直接关联吧。
再次感谢支持。
